# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node >= 8.0'
  inputs:
    versionSpec: '>= 8.0'

- task: YarnInstaller@3
  inputs:
    versionSpec: '>= 1.10.1'

- task: CmdLine@2
  inputs:
    script: 'dotnet tool restore'

- task: CmdLine@2
  inputs:
    script: 'dotnet fake build --target bundle'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: deploy
  condition: succeededOrFailed()

