# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  major: 18
  minor: $[counter(variables['major'], 0)]

steps:
- bash: echo $(major)
- bash: echo $(minor)
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: android-manifest-version@1
  inputs:
    sourcePath: 'Memory.Android/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionName: '$(major).0.$(Build.BuildId)'
    printFile: true

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.fsproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksignerKeystoreFile: 'memoria.keystore'
    apksignerKeystorePassword: '$(apksignerKeystorePassword)'
    apksignerKeystoreAlias: 'memoria'
    apksignerKeyPassword: '$(apksignerKeystorePassword)'
    zipalign: true

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'talbottmike-outlook.com/Memory'
    appFile: '$(outputDirectory)/*.apk'
    # appFile: '$(build.artifactstagingdirectory)/*.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'file'
    releaseNotesFile: 'RELEASE_NOTES.md'
    destinationType: 'store'
    destinationStoreId: '$(googleplay-beta-storeid)'

    