module Client.FlashCardInfo 
open Shared.Domain.FlashCards

let allFlashCards = 
  [ 
    (1,"nauta, nautae","sailor") 
    (1,"terra, terrae","earth, land") 
    (1,"porta, portae","gate") 
    (1,"silva, silvae","forest") 
    (2,"gladius, gladii","sword") 
    (2,"servus, servi","slave, servant") 
    (2,"caelum, caeli","sky,heaven") 
    (2,"filius, filii","son") 
    (2,"amicus, amici","friend") 
    (2,"romanus, romani","roman") 
    (3,"dux, ducis","leader") 
    (1,"Maria, Mariae","Mary") 
    (1,"gloria, gloriae","fame, glory") 
    (2,"vicerunt","they conquered") 
    (2,"videtis","you (plural) see") 
    (2,"incolunt","they inhabit") 
    (1,"victoria, victoriae","victory") 
    (2,"propter","on account of") 
    (2,"Roma, Romae","Rome") 
    (2,"Gallus, Galli","a Gaul") 
    (2,"Gallia, Galliae","Gaul")
    (2,"oppidum, oppidi","town") 
    (2,"Christus, Christi","Christ") 
    (2,"periculum, periculi","danger") 
    (2,"regnum, regni","kingdom, royal power") 
    (2,"bellum, belli","war") 
    (2,"Christianus, Christiani","Christian") 
    (2,"imperium, imperii","comand, power, empire") 
    (2,"Deus, Dei","God") 
    (2,"praemium, praemii","reward") 
    (15,"adjuvo, adjuvare, adjuvi, adjutus","help,aid")
    (17,"administro","manage, attend to")
    (17,"appello","address, call (upon)")
    (15,"colloco","place, station")
    (21,"comparo","get, prepare")
    (17,"confirmo","encourage, strengthen")
    (17,"conservo","preserve, spare")
    (9,"do, dare, dedi, datus","give")
    (21,"exploro","reconnoiter, find out")
    (15,"incito","incite, arouse")
    (9,"laudo","praise")
    (9,"occupo","seize")
    (9,"oppugno","attack, assault, storm")
    (9,"oro","beg, pray")
    (9,"paro","prepare, get ready")
    (15,"perturbo","confuse, disturb")
    (9,"porto","carry")
    (9,"pugno","fight")
    (15,"servo","guard, keep")
    (9,"supero","overcome, conquer, surpass")
    (9,"voco","call")
    (15,"compleo, complere, complevi, completus","fill (with)")
    (18,"contineo, continere, continui, contentus","restrain, hold in")
    (10,"habeo","have")
    (15,"maneo, manere, mansi, mansurus","remain")
    (10,"moneo","warn, advise")
    (11,"moveo, movere, movi, motus","move")
    (18,"obtineo, obtinere, obtinui, obtentus","hold, occupy")
    (21,"retineo, retinere, retinui, retentus","hold back, keep")
    (11,"sustineo, sustinere, sustinui, sustentus","sustain, withstand")
    (11,"teneo, tenere, tenui, tentus","hold")
    (10,"terreo","terrify")
    (9,"timeo, timere, timui","fear")
    (11,"video, videre, vidi, visus","see")
    (12,"ago, agere, egi, actus","drive, do, act, treat, give (w. gratias)")
    (15,"cedo, cedere, cessi, cessurus","give way, yeild")
    (12,"contendo, contendere, contendi","strive, contend, hasten")
    (12,"defendo, defendere, defendi, defensus","defend")
    (19,"dimitto, dimittere, dimisi, dimissus","send away, dismiss")
    (12,"duco, ducere, duxi, ductus","lead, guide")
    (12,"gero, gerere, gessi, gestus","carry, carry on, wage (w. bellum)")
    (15,"incendo, incendere, incendi, incensus","set fire to, burn")
    (12,"instruo, instruere, instruxi, instructus","draw up, equip")
    (12,"mitto, mittere, misi, ,missus","send")
    (19,"occido, occidere, occidi, occisus","kill")
    (12,"pello, pellere, pepuli, pulsus","drive, repulse, rout")
    (12,"peto, petere, petivi, petitus","seek, beg, request")
    (12,"pono, ponere, posui, positus","put, place, set, pitch (w. castra)")
    (21,"premo, premere, pressi, pressus","press, press hard")
    (19,"trado, tradere, tradidi, traditus","hand over")
    (12,"vinco, vinere, vici, victus","conquer")
    (13,"audio","hear")
    (13,"convenio, convenire, conveni, conventum","come together, assemble")
    (13,"munio","fortify, construct (w. viam or vias)")
    (13,"venio, venire, veni, ventum","come")
    (14,"absum, abesse, afui, afuturus; ab (a)","am away, am distant")
    (14,"sum, esse, fui, futurus","am")
    (16,"fortuna, ae","fortune")
    (16,"Italia, ae","Italy")
    (12,"litterae, litterarum","letter (i.e. an epistle), dispatch")
    (16,"ager, ageri","field")
    (9,"locus, i (pl., loca, locorum)","place")
    (9,"numerus, i","number")
    (16,"puer, pueri","boy")
    (16,"vir, viri","man")
    (10,"arma, armorum","arms")
    (1,"orat","he, she, it prays") 
    (1,"orant","they pray") 
    (1,"videt","he, she, it sees")   
    (1,"vident","they see")   
    (1,"non","not") 
    (1,"laudat","he, she, it praises")   
    (1,"laundant","they praise")   
    (1,"provincia, ae","province") 
    (2,"et","and") 
    (2,"dedit","he, she, it gave") 
    (2,"dederunt","they gave") 
    (2,"sed","but") 
    (2,"cum","with") 
    (2,"post","after, behind") 
    (2,"in (abl.)","in, on") 
    (2,"quod","because") 
    (2,"itaque","therefore, and so") // Lesson 2, Conjugation
    (3,"lex, legis","law") 
    (3,"rex, regis","king") 
    (3,"lux, lucis","light") 
    (3,"homo, hominis","man") 
    (3,"imperator, imperatoris","commander in chief, general") 
    (3,"veritas, veritatis","truth") 
    (3,"Caesar, Caesaris","Caesar") 
    (3,"salus, salutis","safety, welfare, salvation") 
    (3,"vox, vocis","voice, cry") 
    (3,"audivit","he, she, it heard") 
    (3,"virtus, virtutis","courage, virtue") 
    (3,"miles, militis","soldier") 
    (3,"pax, pacis","peace") 
    (3,"via, ae","road, way") 
    (3,"populus, i","people, nation") 
    (3,"muniverunt","they fortified, they constructed (w. viam or vias)") 
    (3,"pars, partis","part") 
    (3,"collis, collis","hill") // M.
    (3,"hostis, hostis","enemy (in war)") 
    (3,"gens, gentis","tribe") 
    (3,"caedes, caedis","slaughter") 
    (3,"frater, fratris (fratrum)","brother") 
    (3,"pater, patris (patrum)","father") 
    (3,"mater, matris (matrum)","mother") 
    (3,"mons, montis","mountain") // M.
    (3,"clamor, clamoris","shouting, shout") 
    (3,"princeps, principis","chief, leading man") 
    (3,"occiderunt","they killed") 
    (3,"flumen, fluminis","river") 
    (3,"iter, itineris","journey, march, route") // N.
    (3,"corpus, corporis","body") // N.
    (3,"vulnus, vulneris","wound") // N.
    (3,"agmen, agminis","column (of soldiers), army (on the march)") 
    (3,"nomen, nominis","name") 
    (3,"mundus, i","world") 
    (3,"erat","he, she, it was") 
    (3,"erant","they were") 
    (4,"adventus, us","arrival, coming") 
    (4,"equitatus, us","cavalry") 
    (4,"exercitus, us","army") 
    (4,"impetus, us","attack") 
    (4,"metus, us","fear") 
    (4,"spiritus, us","breath, spirit") 
    (4,"portus, us","harbor") 
    (4,"senatus, us","senate") 
    (4,"in (acc)","in, into, against, upon, on") 
    (4,"nunc","now") 
    (4,"autem","however") 
    (4,"fecerunt","they made") 
    (4,"venit","he, she, it came") 
    (4,"venerunt","they came") 
    (5,"res, rei","thing, affair") 
    (5,"fides, fidei","faith, reliability") 
    (5,"acies, aciei","battle line") 
    (5,"spes, spei","hope") 
    (5,"posuerunt","they put, they placed") 
    (6,"castra, castrorum","camp")
    (6,"impedimenta, impedimentorum","baggage, baggage train")
    (6,"gratia, ae","favor, influence, grace (in Christian Latin)")
    (6,"gratiae, gratiarum","thanks")
    (6,"copia, ae","supply, abundance")
    (6,"copiae, copiarum","troops, forces (a military term)") //Fem.
    (6,"agunt","they give (w. gratias)")
    (7,"mangus, a, um","great, large")
    (6,"posuerunt","they put, they placed, they pitched (w. castra)")
    (7,"altus, a, um","high, deep")
    (7,"bonus, a, um","good")
    (7,"longus, a, um","long")
    (7,"malus, a, um","bad")
    (7,"multus, a, um","much (pl., many)")
    (7,"sanctus, a, um","holy, saint")
    (7,"primus, a, um","first")
    (7,"angustus, a, um","narrow")
    (7,"reliquus, a, um","remaining, the rest of")
    (7,"tutus, a, um","safe")
    (7,"Romanus, a, um","Roman")
    (7,"Christianus, a, um","Christian")
    (7,"pro","in front of (before), on behalf of (for)") 
    (7,"inopia, ae","scarcity, want")
    (7,"dominus, i","master, lord")
    (7,"murus, i","wall")
    (7,"frumentum, i","grain (pl., crops)")
    (7,"legio, legionis","legion") 
    (8,"gravis, e","heavy, severe, serious")
    (8,"brevis, e","short")
    (8,"communis, e","common")
    (8,"difficilis, e","dificult")
    (8,"facilis, e","easy")
    (8,"fortis, e","brave, strong")
    (8,"nobilis, e","noble, renowned")
    (8,"omnis, e","all, every")
    (8,"cupidus, a, um","eager, desirous") 
    (8,"plenus, a, um","full") 
    (8,"finitimus, a, um","neighboring, next")
    (8,"similis, e","like, similar") 
    (8,"Jesus, u","Jesus")
    (8,"et...et","both...and")
    (8,"quid","what?")
    (8,"prima luce","at dawn")
    (8,"urbs, urbis","city")
    (8,"pons, pontis","bridge")
    (8,"signum, i","standard, signal, sign")
    (8,"eques, equitis","horseman (pl., calvary)")
    (9,"centurio, centurionis","a centurion")
    (9,"interim","meanwhile")
    (9,"mors, mortis","death")
    (9,"hiberna, hibernorum","winter quarters")
    (9,"ubi","where?")
    (9,"quis","who?")
    (9,"cur","why?")
    (9,"alienus, a, um","unfavorable, another's, foreign")
    (9,"oratio, orationis","speech, prayer")
    (9,"semper","always")
    (9,"sicut","as")
    (9,"in saecula saeculorum","world without end, forever")
    (9,"-ne","particle used in questions")
    (11,"ego, mei","I")
    (11,"nos, nostri","we")
    (11,"saepe","often")
    (11,"tu, tui","you (singular)")
    (11,"vos, vestri","you (plural)")
    (11,"tamen","nevertheless")
    (11,"neque","nor, and...not")
    (11,"is, ea, id","he, she, it")
    (11,"fines, finium","territory")
    (11,"sui","himself, herself, itself, themselves")
    (11,"etiam","also")
    (11,"enim","for")
    (12,"fortiter","bravely, strongly")
    (12,"ibi","there")
    (12,"de","concerning, about")
    (13,"per","through")
    (14,"undique","from all sides, on all sides")
    (14,"telum, i","dart")
    (14,"longe","far, by far")
    (15,"atque (ac)","and")
    (15,"tum","then, at that time")
    (16,"ita","so, thus")
    (16,"trans","across")
    (16,"meus, a, um","my, mine")
    (16,"noster, nostra, nostrum","our, ours")
    (16,"tuus, a, um","your, yours (singular)")
    (16,"vester, vestra, vestrum","your, yours (plural)")
    (17,"nam","for (when for means because and introduces a reason)")
    (17,"ab (a)","by (expressing agency), from (w. absum)")
    (18,"aut","either...or")
    (18,"aut...aut","either...or")
    (18,"neque...neque","neiter...nor")
    (18,"postea","afterwards")
    (19,"sine","without")
    (19,"fere","almost")
    (21,"vehementer","greatly, violently")
    (22,"vita, ae","life")
    (22,"vallum, i","wall, rampart")
    (22,"amicitia, ae","friendship")
    (22,"fossa, ae","ditch")
    (22,"celeriter","swiftly")
    (22,"exspecto","wait for, wait")
    (22,"novus, a, um","new")
    (22,"diu","a long time, long")
    (22,"acriter","ditterly, eagerly")
    (22,"expugno","storm, take by storm")
    (23,"tribunus, i","tribune")
    (23,"consilium, i","plan, counsel")
    (23,"concilium, i","council")
    (23,"legatus, i","envoy, lieutenant")
    (23,"latus, a, um","wide")
    (23,"facile","easily")
    (23,"labor, laboris","effort, toil")
    (23,"ordo, ordinis","rank (of soldiers)") // M.
    (23,"obses, obidis","hostage") // c.
    (23,"inter","between, among")
    (23,"statim","at once, immediately")
    (24,"qui, quae, quod","who (whose, whom), which, that")
    (24,"auxilium, i","help, aid")
    (24,"memoria, ae","memory")
    (24,"memoria teneo, tenere, tenui, tentus","keep in memory, remember")
    (24,"ad","to, until, for (with adjectives)")
    (24,"usque","all the way")
    (24,"pervenio, pervenire, perveni, perventum","arrive")
    (24,"pertineo, pertinere, pertinui","pertain to, stretch to")
    (24,"paratus, a, um","prepared (for)")
    (24,"utilis, e","useful (for)")
    (24,"nox, noctis","night")
    (24,"deduco, deducere, deduxi, deductud","lead, lead away")
    (24,"cognosco, cognoscere, cognovi, cognitus","learn, find out")
    (24,"nuntius, i","messenger, message")
    (24,"natura, ae","nature")
    (24,"-que","and")
    (24,"injuria, ae","injustice, wrong")
    (24,"diutius","longer")
    (24,"facilius","more easily")
    (24,"appropinquo","draw near to, approach")
    (24,"vasto","lay waste, ravage")
    (24,"custos, custodis","guard")
    (25,"unde","whence? from what place? where...from?")
    (25,"quo","whither? where...(to)? to what place?")
    (25,"certus, a, um","certain, sure")
    (25,"barbarus, a, um","barbarian")
    (25,"apud","among, in the presence of")
    (25,"plurimum","very, very much")
    (25,"valeo, valere, valui, valiturus","am strong, am well, am influential")
    (25,"cerno, cernere","distinguish, see")
    (25,"ostendo, ostendere, ostendi, ostentus","show")
    (25,"traduco, traducere, traduxi, traductus","lead across")
    (25,"clam","secretly")
    (25,"socius, i","ally")
    (25,"quis, quid","who? what?")
    (25,"qui, quae, quod","which? what?")
    (26,"incolo, incolere, incolui","inhabit, dwell in")
    (26,"consisto, consistere, constiti","halt, take position")
    (26,"rogo","ask")
    (26,"quaero, quaerere, quaesivi, quaesitus","seek, ask")
    (26,"quantus, a, um","how large? how great?")
    (26,"munitio, munitionis","fortification")
    (26,"genus, generis","kind, race") // N.
    (26,"aqua, ae","water")
    (26,"cogo, cogere, coegi, coactus","collect, force")
    (26,"verus, a, um","true")
    (26,"inquit","he says, he said")
    (27,"ave!","hail!")
    (27,"mora, ae","delay")
    (27,"doceo, docere, docui, doctus","teach, inform")
    (27,"tollo, tollere, sustuli, sublatus","raise (up), take away")
    (27,"peccatum, i","mistake, sin (in Christian Latin)")
    (27,"rego, regere, rexi, rectus","direct, rule")
    (27,"at","but")
    (27,"mens, mentis","mind")
    (27,"dolor, doloris","pain, sorrow")
    (27,"misere nobis","have mercy on us")
    (27,"adoro","adore")
    (28,"suus, a, um","his (own), her (own), its (own), their (own)")
    (28,"fuga, ae","flight")
    (28,"dedo, dedere, dedidi, deditus","give up, surrender")
    (28,"res publica, rei publicae","state, republic")
    (28,"diligo, diligere, dilexi, dilectus","love")
    (28,"ante","before")
    (28,"praesidium, i","garrison, protection")
    (28,"vero","in truth, but")
    (29,"parvus, a, um","small, little")
    (29,"mos, moris","custom, habit") // M.
    (29,"manus, us","a band of men, hand") // F.
    (29,"causa, ae","cause")
    (29,"causa","for the sake of")
    (29,"scio, scire, scivi, scitus","know")
    (29,"paco","pacify")
    (29,"subito","suddenly")
    (29,"probo","approve, prove")
    (29,"relinquo, relinquere, reliqui, relictus","leave, leave behind")
    (30,"adduco, adducere, adduxi, adductus","lead to, lead on")
    (30,"commoveo, commovere, commovi, commotus","alarm, arouse")
    (30,"impedio","hinder, impede")
    (30,"auctoritas, auctoritatis","authority, influence")
    (31,"contra","against, opposite")
    (31,"a tergo","in the rear, from the rear")
    (31,"a fronte","in the front, from the front")
    (31,"summus, a, um","highest, greatest, very great")
    (32,"discedo, discedere, discessi, discessurus","depart, withdraw")
    (32,"navis, navis","ship")
    (32,"ex (e)","out of, from")
    (32,"ab (a)","away from, from")
    (32,"de","down from, from")
    (32,"cado, cadere, cecidi, casurus","fall")
    (33,"is, ea, id","that (as a demonstrative), he, she, it (as a personal pronoun)")
    (33,"ille, illa, illud","that (as a demonstrative), he, she, it (a personal pronoun)")
    (33,"numquam","never")
    (33,"praeterea","besides, furthermore")
    (33,"ratio, rationis","reason, manner")
    (34,"libero","free (from)")
    (34,"vacuus, a, um","empty (of)")
    (34,"liber, libera, liberum","free (from)")
    (34,"prohibeo","ward off (from), prevent")
    (35,"possum, posse, potui","am able, can")
    (35,"adversus, a, um","facing (towards), unfavorable")
    (35,"proximus, a, um","nearest, next")
    (35,"jam","already, now (at that time)")
    (35,"primum","first")
    (35,"constituo, constituere, constitui, constitutus","place, set up, decide, determine")
    (35,"consuevi, consuetus","have accustomed, have become accustomed, am accustomed")
    (35,"sententia, ae","opinon, vote")
    (35,"regio, regionis","region")
    (35,"omnino","at all (with negatives like non), altogether, in all (with numerals)")
    (35,"jubeo, jubere, jussi, jussus","order, command")
    (35,"oportet, oportere, oportuit","it behooves")
    (35,"timor, timoris","fear")
    (36,"quot","how many?")
    (36,"aeternus, a, um","eternal, everlasting")
    (36,"caput, capitis","head")
    (36,"alius, alia, aliud","other, another (of more than two)")
    (36,"alter, altera, alterum","the one, the other (of two)")
    (36,"uter, utra, utrum","which? (of two)")
    (36,"neuter, neutra, neutrum","neither (of two)")
    (36,"ullus, a, um","no, none")
    (36,"nullus, a, um","no, none")
    (36,"solus, a, um","alone, only (as adjective)")
    (36,"totus, a, um","whole, all of, the whole of")
    (37,"capio, capere, cepi, captus","take, capture")
    (37,"fugio, fugere, fugi, fugiturus","flee")
    (37,"facio, facere, feci, factus","do, make")
    (37,"voluntas, voluntatis","good will, will")
    (37,"annus, i","year")
    (37,"vigilia, ae","watch")
    (37,"tempus, temporis","time") // N.
    (37,"dies, diei","day") // N. (F.)
    (37,"hora, ae","hour")
    (37,"primus, a, um","first")
    (37,"secundus, a, um / alter, altera, alterum","second")
    (37,"tertius, a, um","third")
    (37,"conjicio, conjicere, conjeci, conjectus","throw, hurl")
    (37,"recipio, recipere, recepi, receptus","receive, accept, recover")
    (37,"(with a reflexive pronoun) me, te, se, etc.","withdraw")
    (37,"cupio, cupere, cupivi, cupitus","desire")
    (37,"rursus","again")
    (37,"pes, pedis","foot (part of a body or measure of distance)")
    (37,"passus, us","pace (a measure of distance = 5 Roman feet [pedes])")
    (37,"mille","thousand")
    (37,"mille passus","miles (literally, a thousand paces = 1,618 English yards)")
    (37,"millia, milium","thousands") // N.
    (37,"quam","how?")
    (37,"interficio, interficere, interfeci, interfectus","kill")
    (37,"eripio, eripere, eripui, ereptus","take away, save (from)")
    (37,"nihil","nothing")
    (37,"conspicio, conspicere, conspexi, conspectus","see, catch sight of")
    (37,"accipio, accipere, accepi, acceptus","receive, accept")
    (37,"conficio, conficere, confeci, confectus","finish, wear out")
    (37,"nemo, neminis","no one") // M.
    (37,"magnitudo, magnitudinis","size, greatness")
    (37,"satis","enough, sufficiently")
    (37,"animus, i","mind, soul")
    (37,"satis","enough")
    (38,"noceo, nocere, nocui, nociturus","do harm to, injure")
    (38,"praesum, praeesse, praefui, praefuturus","am in command of, am in charge of")
    (38,"mare, maris","sea")
    (38,"ventus, i","wind")
    (38,"navigo","sail")
    (39,"dico, dicere, dixi, dictus","say, tell")
    (39,"respondeo, respondere, respondi, responsus","answer")
    (39,"puto","think")
    (39,"scio","know")
    (39,"audio","hear")
    (39,"scribo, scribere, scripsi, scriptus","write")
    (39,"reperio, reperire, repperi, repertus","find (out)")
    (39,"nego","deny, say...not")
    (39,"nuntio","announce, report")
    (39,"demonstro","show, point out")
    (39,"existimo","think")
    (39,"sentio, sentere, sensi, sensus","feel, perceive, think")
    (40,"aestimo","think")
    (40,"judico","judge")
    (40,"quam","than")
    (40,"certiorem (-es) facere","to inform")
    (41,"conor, conari, conatus sum","try, attempt")
    (41,"vereor, vereri, veritus sum","fear")
    (41,"sequor, sequi, secutus sum","follow")
    (41,"patior, pati, passus sum","suffer, allow")
    (41,"orior, oriri, ortus sum","rise, arise")
    (41,"polliceor, polliceri, pollicitus sum","promise")
    (41,"loquor, loqui, locutus sum","speak, talk")
    (41,"proficiscor, proficisci, profectus sum","set out")
    (41,"nactus","having obtained, having found")
    (41,"egredior, egredi, egressus sum","go out")
    (41,"progredior, progredi, progressus sum","think, consider")
    (41,"arbitror, arbitrari, arbitratus sum","advance")
    (41,"hortor, hortari, hortatus sum","urge, encourage")
    (42,"eo, ire, ivi (ii), itum","go")
    (42,"exeo, exire, exii, exitum","go out")
    (42,"ineo, inire, inii, initus","go into, enter upon")
    (42,"transeo, transire, transii, transitus","go across, cross")
    (42,"redeo, redire, redii, reditum","return")
    (42,"adeo, adire, adii, aditus","go to, approach, visit")
  ]
  |> List.map (fun (l,q,a) ->
    {
        Lesson = "Lesson " + l.ToString()
        Front = { Question = q }
        Back = { Answer = a }
    }  
  )